tplProjectName: mobilebuilder_tpl_8_0_0_ngx
â†“LoginComponent [ngx.components.UISharedComponent-1572604124714]: ğŸ— mobileSharedComponents/LoginComponent.yaml
â†“ForgotPassword [ngx.components.UISharedComponent-1582131761883]: ğŸ— mobileSharedComponents/ForgotPassword.yaml
â†“Page [ngx.components.PageComponent-1572604056200]: ğŸ— mobilePages/Page.yaml
â†“ModalPopup [ngx.components.PageComponent-1572623654326]: ğŸ— mobilePages/ModalPopup.yaml
â†“ForgotPasswordPage [ngx.components.PageComponent-1582131661217]: ğŸ— mobilePages/ForgotPasswordPage.yaml